server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    #不要注册向中心自己
    register-with-eureka: false
    #false自己就是注册中心，职责就是维护服务实例，不需要检索服务
    fetch-registry: false
    service-url:
      #设置Eureka sever交互的地址查询服务和注册服务都需要依赖这个地址
       defaultZone: http://eureka7001.com:7001/eureka/
