server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
        enabled: true   #开启注册中心，并且又微服务名称来进行路由
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service
#          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**

        - id: payment_routh2
          uri: lb://cloud-payment-service
#          uri: http://localhost:8001
          predicates:
            -  Path=/payment/lb/**
            -  After=2020-03-23T23:45:33.582+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id,\d+         #请求头必须带改键值对

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
